apiVersion: v2
name: backend
description: DAVe traffic counting plattform, backend
type: application
version: 3.0.1
appVersion: "3.0.1-SNAPSHOT-9"
maintainers:
  - name: klml
    email: klml@muenchen.de
  - name: Starwit Technologies GmbH
    email: foss@starwit.de
home: https://github.com/it-at-m/helm-charts/tree/main/charts/dave/charts/backend
#icon: https://raw.githubusercontent.com/it-at-m/helm-charts/main/images/logo.png
sources:
  - "https://github.com/it-at-m/helm-charts"
  - "https://github.com/it-at-m/dave-backend-postgres"
