apiVersion: v2
name: dave-backend-chart
description: DAVe traffic counting plattform, backend
type: application
version: ${project.version}
appVersion: "${project.version}"
maintainers:
  - name: klml
    email: klml@muenchen.de
  - name: Starwit Technologies GmbH
    email: foss@starwit.de
home: https://github.com/it-at-m/helm-charts/tree/main/charts/dave/charts/backend
#icon: https://raw.githubusercontent.com/it-at-m/helm-charts/main/images/logo.png
sources:
  - "https://github.com/it-at-m/helm-charts"
  - "https://github.com/it-at-m/dave-backend-postgres"
