name: dave-stack

services:
  postgres:
    image: postgres:16.6-alpine3.21
    environment:
      - POSTGRES_DB=dave-db
      - POSTGRES_USER=dave
      - POSTGRES_PASSWORD=1234
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck: &healthcheck
      test: [ "CMD-SHELL", "pg_isready -d postgres -U dave" ]
      interval: 30s
      timeout: 60s
      retries: 3
      start_period: 60s
    security_opt: &security_settings
      - no-new-privileges:true

  # see https://event-driven.io/en/automatically_connect_pgadmin_to_database/
  pg-admin:
    image: dpage/pgadmin4:8.14
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    healthcheck:
      <<: *healthcheck
      test: [ "CMD", "wget", "-O", "-", "http://localhost:5050/misc/ping" ]
    security_opt: *security_settings
    volumes:
      - './pgadmin/servers.json:/pgadmin4/servers.json:ro'
      - './pgadmin/pgpass:/pgadmin4/pgpass'
    user: root # see https://github.com/pgadmin-org/pgadmin4/issues/6257
    entrypoint: /bin/sh -c "chmod 600 /pgadmin4/pgpass; /entrypoint.sh;" # see https://www.postgresql.org/docs/current/libpq-pgpass.html#LIBPQ-PGPASS (last paragraph)

#https://hub.docker.com/_/elasticsearch
#https://www.elastic.co/guide/en/elasticsearch/reference/8.13/docker.html
#https://medium.com/@lopchannabeen138/deploying-elk-inside-docker-container-docker-compose-4a88682c7643
  elasticsearch:
    image: elasticsearch:8.13.4
    container_name: elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data/
      - es_config:/usr/share/elasticsearch/config/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - http.host:0.0.0.0
    networks:
      - elk

networks:
  elk:

volumes:
  es_data:
  es_config:
  pg_data: